### PR TITLE
Add travis-ci configuration

### PR DESCRIPTION
**Pull request by jwillemsen**
Adding a travis-ci configuration, please open an account on travis-ci.org so that there is a CI. After that a badge can be added to the readme.md

### CODE REVIEW

**Comment by jwillemsen** [comment]
WIth this travis file as example maybe to all sodaqmoja repo's a travis-ci configuration can be added? Hopefully at some point platformio fixes the warning and we could enable -Werror

**Comment by jwillemsen** [comment]
Any plans to merge this?

**Comment by keestux** [comment]
Can you do a squash?

**Comment by jwillemsen** [comment]
Github has a squash and merge option for pull requests, maybe you have to allow it in the project settings? That is the easiest to do

**Comment by keestux** [comment]
When I asked for a squash I was expecting that you do it in your own local repo. And then do a forced push to update the PR branch. (( That's how we do things in RIOT-OS, for example. ))

**Comment by jwillemsen** [comment]
Can do that tomorrow, personally I don't like forced updates but just use the squash commit feature from github

**Comment by jwillemsen** [comment]
@keestux Done, squashed to one change

**Pull request merged**
