### PR TITLE
Add github action for CI

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by SodaqMoja** [comment]
Hey @jwillemsen Thanks for the PR. Can you squash the last 5 commits? I don't see the need to keep them separate.

**Comment by jwillemsen** [comment]
Will squash tomorrow

**Comment by jwillemsen** [comment]
squashed

**Comment by SodaqMoja** [comment]
@jwillemsen this PR is not as clean as I was hoping for (same story as [RN2483 PR25](https://github.com/SodaqMoja/Sodaq_RN2483/pull/25)

It merges your own master (5b3161b6) which is not the same as our master (4396fb942). I want that the "Add github action" commit is based on our master, not yours.

**Comment by jwillemsen** [comment]
I think in the past 094b036be3ecf5d0ad22f09e9f4542495307ca3f got strangely merged. You could do a squash merge or I have to delete my fork and create a fresh fork and reapply the changes. Will look at that tomorrow

**Comment by SodaqMoja** [comment]
I see this happens when people do a git-pull after they have locally merged or added commits. I'm a command line guy, and I usually do `git pull --rebase --prune`. Every GUI can do the same. The golden rule is: check your git commit tree afterwards and make a judgement if the pull result is what you want.

Another golden rule (at least for me) is that the `master` of the origin is leading.

**Comment by jwillemsen** [comment]
Thanks, will try that tomorrow, also using mostly commandline here but in most projects I try not to rewrite history.

**Pull request closed without merging**
